add result check

diff --git a/.github/workflows/conformance.yml b/.github/workflows/conformance.yml
--- a/.github/workflows/conformance.yml
+++ b/.github/workflows/conformance.yml
@@ -1,9 +1,11 @@
 name: Conformance tests
 
 on:
-  push:
-    branches: [master]
-  workflow_dispatch:
+  pull_request:
+    branches:
+      - master
+    path:
+      - 'features/**'
 
 jobs:
   demo-ts:
@@ -63,3 +65,24 @@ jobs:
 
       - name: Run library tests against the spec
         run: make -C demo-dotnet test
+
+  result:
+    name: conformance-result
+    runs-on: ubuntu-latest
+    needs: [demo-ts, demo-dotnet]
+    if: always()
+    steps:
+      - name: Check all tests passed
+        run: |
+          if [[ \
+            "${{ needs.demo-ts.result }}" == "success" && \
+            "${{ needs.demo-dotnet.result }}" == "success" && \
+            "${{ needs.mutation-ts.result }}" == "success" && \
+            "${{ needs.mutation-dotnet.result }}" == "success" \
+          ]]; then
+            echo "All tests passed"
+            exit 0
+          else
+            echo "Some tests failed: demo-ts=${{ needs.demo-ts.result }}, demo-dotnet=${{ needs.demo-dotnet.result }}, mutation-ts=${{ needs.mutation-ts.result }}, mutation-dotnet=${{ needs.mutation-dotnet.result }}"
+            exit 1
+          fi
